export enum ChainId {
	MAINNET = 1,
	OPTIMISM = 10,
	CRONOS = 25,
	ROOTSTOCK = 30,
	ROOTSTOCK_TESTNET = 31,
	BSC = 56,
	BSC_TESTNET = 97,
	GNOSIS = 100,
	UNICHAIN = 130,
	POLYGON = 137,
	MONAD = 143,
	SONIC = 146,
	OPBNB = 204,
	LENS = 232,
	FRAXTAL = 252,
	BOBA = 288,
	ZKSYNC_SEPOLIA = 300,
	ZKSYNC = 324,
	CRONOS_TESTNET = 338,
	SHAPE = 360,
	WORLDCHAIN = 480,
	FLOW_TESTNET = 545,
	ASTAR = 592,
	FLOW = 747,
	MODE_SEPOLIA = 919,
	STABLE = 988,
	HYPEREVM_TESTNET = 998,
	HYPEREVM = 999,
	METIS = 1088,
	MOONBEAM = 1284,
	UNICHAIN_SEPOLIA = 1301,
	DATA_NETWORK_AENEID = 1315,
	SEI_TESTNET = 1328,
	SEI = 1329,
	DATA_NETWORK = 1514,
	SONEIUM = 1868,
	SONEIUM_MINATO = 1946,
	RONIN = 2020,
	STABLE_TESTNET = 2201,
	FRAXTAL_HOODI = 2523,
	ABSTRACT = 2741,
	RISE = 4153,
	MEGAETH = 4326,
	ROBINHOOD = 4663,
	WORLDCHAIN_SEPOLIA = 4801,
	MANTLE = 5000,
	MANTLE_SEPOLIA = 5003,
	ARC = 5042,
	SUPERSEED = 5330,
	OPBNB_TESTNET = 5611,
	MEGAETH_TESTNET = 6343,
	ZETACHAIN = 7000,
	ZETACHAIN_TESTNET = 7001,
	BASE = 8453,
	PLASMA = 9745,
	PLASMA_TESTNET = 9746,
	MONAD_TESTNET = 10143,
	GNOSIS_CHIADO = 10200,
	SHAPE_SEPOLIA = 11011,
	ABSTRACT_TESTNET = 11124,
	SONIC_TESTNET = 14601,
	BOBA_SEPOLIA = 28882,
	APECHAIN_CURTIS = 33111,
	APECHAIN = 33139,
	MODE = 34443,
	LENS_SEPOLIA = 37111,
	ARBITRUM = 42161,
	ARBITRUM_NOVA = 42170,
	CELO = 42220,
	HEMI = 43111,
	AVALANCHE_FUJI = 43113,
	AVALANCHE = 43114,
	ROBINHOOD_TESTNET = 46630,
	SUPERSEED_SEPOLIA = 53302,
	INK = 57073,
	LINEA_SEPOLIA = 59141,
	LINEA = 59144,
	BOB = 60808,
	POLYGON_AMOY = 80002,
	BERACHAIN_BEPOLIA = 80069,
	BERACHAIN = 80094,
	BLAST = 81457,
	BASE_SEPOLIA = 84532,
	RONIN_SAIGON = 202601,
	ARBITRUM_SEPOLIA = 421614,
	SCROLL_SEPOLIA = 534351,
	SCROLL = 534352,
	HOODI = 560048,
	GENSYN_TESTNET = 685685,
	GENSYN = 685689,
	KATANA_BOKUTO = 737373,
	HEMI_SEPOLIA = 743111,
	KATANA = 747474,
	INK_SEPOLIA = 763373,
	BOB_SEPOLIA = 808813,
	ARC_TESTNET = 5042002,
	ZORA = 7777777,
	CELO_SEPOLIA = 11142220,
	SEPOLIA = 11155111,
	OPTIMISM_SEPOLIA = 11155420,
	RISE_TESTNET = 11155931,
	BLAST_SEPOLIA = 168587773,
	ZORA_SEPOLIA = 999999999,
}

export const ALCHEMY_NETWORKS: Partial<Record<ChainId, string>> = {
	[ChainId.MAINNET]: "eth-mainnet",
	[ChainId.OPTIMISM]: "opt-mainnet",
	[ChainId.CRONOS]: "cronos-mainnet",
	[ChainId.ROOTSTOCK]: "rootstock-mainnet",
	[ChainId.ROOTSTOCK_TESTNET]: "rootstock-testnet",
	[ChainId.BSC]: "bnb-mainnet",
	[ChainId.BSC_TESTNET]: "bnb-testnet",
	[ChainId.GNOSIS]: "gnosis-mainnet",
	[ChainId.UNICHAIN]: "unichain-mainnet",
	[ChainId.POLYGON]: "polygon-mainnet",
	[ChainId.MONAD]: "monad-mainnet",
	[ChainId.SONIC]: "sonic-mainnet",
	[ChainId.OPBNB]: "opbnb-mainnet",
	[ChainId.LENS]: "lens-mainnet",
	[ChainId.FRAXTAL]: "frax-mainnet",
	[ChainId.BOBA]: "boba-mainnet",
	[ChainId.ZKSYNC_SEPOLIA]: "zksync-sepolia",
	[ChainId.ZKSYNC]: "zksync-mainnet",
	[ChainId.CRONOS_TESTNET]: "cronos-testnet",
	[ChainId.SHAPE]: "shape-mainnet",
	[ChainId.WORLDCHAIN]: "worldchain-mainnet",
	[ChainId.FLOW_TESTNET]: "flow-testnet",
	[ChainId.ASTAR]: "astar-mainnet",
	[ChainId.FLOW]: "flow-mainnet",
	[ChainId.MODE_SEPOLIA]: "mode-sepolia",
	[ChainId.STABLE]: "stable-mainnet",
	[ChainId.HYPEREVM_TESTNET]: "hyperliquid-testnet",
	[ChainId.HYPEREVM]: "hyperliquid-mainnet",
	[ChainId.METIS]: "metis-mainnet",
	[ChainId.MOONBEAM]: "moonbeam-mainnet",
	[ChainId.UNICHAIN_SEPOLIA]: "unichain-sepolia",
	[ChainId.DATA_NETWORK_AENEID]: "story-aeneid",
	[ChainId.SEI_TESTNET]: "sei-testnet",
	[ChainId.SEI]: "sei-mainnet",
	[ChainId.DATA_NETWORK]: "story-mainnet",
	[ChainId.SONEIUM]: "soneium-mainnet",
	[ChainId.SONEIUM_MINATO]: "soneium-minato",
	[ChainId.RONIN]: "ronin-mainnet",
	[ChainId.STABLE_TESTNET]: "stable-testnet",
	[ChainId.FRAXTAL_HOODI]: "frax-hoodi",
	[ChainId.ABSTRACT]: "abstract-mainnet",
	[ChainId.RISE]: "rise-mainnet",
	[ChainId.MEGAETH]: "megaeth-mainnet",
	[ChainId.ROBINHOOD]: "robinhood-mainnet",
	[ChainId.WORLDCHAIN_SEPOLIA]: "worldchain-sepolia",
	[ChainId.MANTLE]: "mantle-mainnet",
	[ChainId.MANTLE_SEPOLIA]: "mantle-sepolia",
	[ChainId.ARC]: "arc-mainnet",
	[ChainId.SUPERSEED]: "superseed-mainnet",
	[ChainId.OPBNB_TESTNET]: "opbnb-testnet",
	[ChainId.MEGAETH_TESTNET]: "megaeth-testnet",
	[ChainId.ZETACHAIN]: "zetachain-mainnet",
	[ChainId.ZETACHAIN_TESTNET]: "zetachain-testnet",
	[ChainId.BASE]: "base-mainnet",
	[ChainId.PLASMA]: "plasma-mainnet",
	[ChainId.PLASMA_TESTNET]: "plasma-testnet",
	[ChainId.MONAD_TESTNET]: "monad-testnet",
	[ChainId.GNOSIS_CHIADO]: "gnosis-chiado",
	[ChainId.SHAPE_SEPOLIA]: "shape-testnet",
	[ChainId.ABSTRACT_TESTNET]: "abstract-testnet",
	[ChainId.SONIC_TESTNET]: "sonic-testnet",
	[ChainId.BOBA_SEPOLIA]: "boba-sepolia",
	[ChainId.APECHAIN_CURTIS]: "apechain-curtis",
	[ChainId.APECHAIN]: "apechain-mainnet",
	[ChainId.MODE]: "mode-mainnet",
	[ChainId.LENS_SEPOLIA]: "lens-sepolia",
	[ChainId.ARBITRUM]: "arb-mainnet",
	[ChainId.ARBITRUM_NOVA]: "arbnova-mainnet",
	[ChainId.CELO]: "celo-mainnet",
	[ChainId.AVALANCHE_FUJI]: "avax-fuji",
	[ChainId.AVALANCHE]: "avax-mainnet",
	[ChainId.ROBINHOOD_TESTNET]: "robinhood-testnet",
	[ChainId.SUPERSEED_SEPOLIA]: "superseed-sepolia",
	[ChainId.INK]: "ink-mainnet",
	[ChainId.LINEA_SEPOLIA]: "linea-sepolia",
	[ChainId.LINEA]: "linea-mainnet",
	[ChainId.BOB]: "bob-mainnet",
	[ChainId.POLYGON_AMOY]: "polygon-amoy",
	[ChainId.BERACHAIN_BEPOLIA]: "berachain-bepolia",
	[ChainId.BERACHAIN]: "berachain-mainnet",
	[ChainId.BLAST]: "blast-mainnet",
	[ChainId.BASE_SEPOLIA]: "base-sepolia",
	[ChainId.RONIN_SAIGON]: "ronin-saigon",
	[ChainId.ARBITRUM_SEPOLIA]: "arb-sepolia",
	[ChainId.SCROLL_SEPOLIA]: "scroll-sepolia",
	[ChainId.SCROLL]: "scroll-mainnet",
	[ChainId.HOODI]: "eth-hoodi",
	[ChainId.GENSYN_TESTNET]: "gensyn-testnet",
	[ChainId.GENSYN]: "gensyn-mainnet",
	[ChainId.KATANA_BOKUTO]: "katana-bokuto",
	[ChainId.KATANA]: "katana-mainnet",
	[ChainId.INK_SEPOLIA]: "ink-sepolia",
	[ChainId.BOB_SEPOLIA]: "bob-sepolia",
	[ChainId.ARC_TESTNET]: "arc-testnet",
	[ChainId.ZORA]: "zora-mainnet",
	[ChainId.CELO_SEPOLIA]: "celo-sepolia",
	[ChainId.SEPOLIA]: "eth-sepolia",
	[ChainId.OPTIMISM_SEPOLIA]: "opt-sepolia",
	[ChainId.RISE_TESTNET]: "rise-testnet",
	[ChainId.BLAST_SEPOLIA]: "blast-sepolia",
	[ChainId.ZORA_SEPOLIA]: "zora-sepolia",
} as const;

export const INFURA_NETWORKS: Partial<Record<ChainId, string>> = {
	[ChainId.MAINNET]: "mainnet",
	[ChainId.OPTIMISM]: "optimism-mainnet",
	[ChainId.BSC]: "bsc-mainnet",
	[ChainId.BSC_TESTNET]: "bsc-testnet",
	[ChainId.UNICHAIN]: "unichain-mainnet",
	[ChainId.POLYGON]: "polygon-mainnet",
	[ChainId.MONAD]: "monad-mainnet",
	[ChainId.OPBNB]: "opbnb-mainnet",
	[ChainId.ZKSYNC_SEPOLIA]: "zksync-sepolia",
	[ChainId.ZKSYNC]: "zksync-mainnet",
	[ChainId.SHAPE]: "shape-mainnet",
	[ChainId.HYPEREVM_TESTNET]: "hyperevm-testnet",
	[ChainId.HYPEREVM]: "hyperevm-mainnet",
	[ChainId.UNICHAIN_SEPOLIA]: "unichain-sepolia",
	[ChainId.SEI_TESTNET]: "sei-testnet",
	[ChainId.SEI]: "sei-mainnet",
	[ChainId.MEGAETH]: "megaeth-mainnet",
	[ChainId.MANTLE]: "mantle-mainnet",
	[ChainId.MANTLE_SEPOLIA]: "mantle-sepolia",
	[ChainId.ARC]: "arc-mainnet",
	[ChainId.OPBNB_TESTNET]: "opbnb-testnet",
	[ChainId.MEGAETH_TESTNET]: "megaeth-testnet",
	[ChainId.BASE]: "base-mainnet",
	[ChainId.MONAD_TESTNET]: "monad-testnet",
	[ChainId.SHAPE_SEPOLIA]: "shape-testnet",
	[ChainId.ARBITRUM]: "arbitrum-mainnet",
	[ChainId.CELO]: "celo-mainnet",
	[ChainId.HEMI]: "hemi-mainnet",
	[ChainId.AVALANCHE_FUJI]: "avalanche-fuji",
	[ChainId.AVALANCHE]: "avalanche-mainnet",
	[ChainId.LINEA_SEPOLIA]: "linea-sepolia",
	[ChainId.LINEA]: "linea-mainnet",
	[ChainId.BLAST]: "blast-mainnet",
	[ChainId.BASE_SEPOLIA]: "base-sepolia",
	[ChainId.ARBITRUM_SEPOLIA]: "arbitrum-sepolia",
	[ChainId.SCROLL_SEPOLIA]: "scroll-sepolia",
	[ChainId.SCROLL]: "scroll-mainnet",
	[ChainId.HOODI]: "hoodi",
	[ChainId.HEMI_SEPOLIA]: "hemi-testnet",
	[ChainId.ARC_TESTNET]: "arc-testnet",
	[ChainId.CELO_SEPOLIA]: "celo-sepolia",
	[ChainId.SEPOLIA]: "sepolia",
	[ChainId.OPTIMISM_SEPOLIA]: "optimism-sepolia",
	[ChainId.BLAST_SEPOLIA]: "blast-sepolia",
} as const;

export const SUPPORTED_CHAINS = Object.entries(ChainId).filter(
	(entry): entry is [keyof typeof ChainId, ChainId] =>
		typeof entry[1] === "number",
);
